title: Zen Payments Docs
description: A starter documentation page for zen
theme: just-the-docs

url: https://ZenPayments.github.io/

logo: "/assets/ZenLogo.png"

favicon_ico : "/assets/favicon.ico"



footer_content: "Copyright © 2023 Zen Payments All Rights Reserved"
